name: "PhD Assignment"
description: "Process multiple PDFs for academic research by summarizing with Claude, collecting in Google Docs, and generating final answer with ChatGPT"

tags:
  - research
  - academic
  - pdf
  - summarization

parameters:
  - name: pdf_files
    description: "List of PDF files to process"
    example: "paper1.pdf, paper2.pdf, paper3.pdf"
  
  - name: research_question
    description: "The research question to be answered"
    example: "What are the main applications and challenges of deep learning in medical imaging?"
  
  - name: summary_prompt
    description: "Custom prompt for summarizing PDFs (optional)"
    default: "Please provide a comprehensive summary of this academic paper, focusing on the main findings, methodology, and conclusions."

workflow:
  - id: "summarize_pdfs"
    name: "Summarize PDFs"
    tool:
      name: "claude"
      model: "Claude 3.5 Sonnet"
      settings:
        enable_artifacts: true
    description: "Use Claude to generate comprehensive summaries of academic papers"
    tool_usage: |
      1. For each PDF file:
         a. Upload the PDF to Claude
         b. Use the summary prompt (default or custom)
         c. Save the generated summary
    prompt: |
      You are a helpful AI research assistant. Your task is to summarize academic papers clearly and accurately.

      Please provide a comprehensive summary of this academic paper, focusing on:
      - Main findings
      - Methodology
      - Conclusions
      - Relevant statistics or data for meta-analysis

      {{summary_prompt}}

  - id: "collect_summaries"
    name: "Collect Summaries"
    tool:
      name: "google_docs"
      settings:
        enable_markdown: true
    description: "Organize paper summaries in a Google Doc"
    tool_usage: |
      1. Create a new Google Doc titled "Research Summaries - [Date]"
      2. Add all PDF summaries with clear section headers
      3. Format for readability
    prompt: |
      Create a new Google Doc with the following structure:

      # Research Summaries
      Date: [Current Date]
      Research Question: {{research_question}}
      
      Files Analyzed: {{pdf_files}}

      ## Paper Summaries
      [Add summaries here with clear headers]

  - id: "generate_answer"
    name: "Generate Answer"
    tool:
      name: "chatgpt"
      model: "GPT-4"
      settings:
        enable_web_search: false
    description: "Generate comprehensive answer to research question"
    tool_usage: |
      1. Upload the Google Doc with summaries
      2. Use the analysis prompt to generate answer
      3. Review and refine the response
    prompt: |
      You are a research assistant helping with a literature review. Based on the following paper summaries, please provide a comprehensive answer to this research question:

      Question: {{research_question}}

      [Paper summaries will be provided here]

      Please structure your answer with:
      1. Executive Summary
      2. Key Findings from Literature
      3. Synthesis and Analysis
      4. Gaps and Future Research
      5. Conclusion

tips:
  - "Use consistent section headers in Google Docs to make the summaries easy to navigate"
  - "Consider adding tags or keywords to each summary for better organization"
  - "If the PDFs are large, you may want to focus Claude's summary on specific sections"
  - "Make sure to include page numbers or section references in the summaries for easy verification"

examples:
  - parameters:
      research_question: "What are the main applications and challenges of deep learning in medical imaging?"
      pdf_files: "paper1.pdf, paper2.pdf, paper3.pdf"
    sample_queries:
      - "Summarize the methodology and findings from the papers regarding deep learning applications in medical imaging"
      - "What are the common challenges and limitations identified across the papers?"