name: Validate Recipes

on:
  push:
    paths:
      - 'recipes/**/*.yaml'
      - 'recipes/**/*.yml'
      - 'schema/**/*.yaml'
      - 'schema/**/*.yml'
  pull_request:
    paths:
      - 'recipes/**/*.yaml'
      - 'recipes/**/*.yml'
      - 'schema/**/*.yaml'
      - 'schema/**/*.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml yamale jsonschema

      - name: Check directory structure
        run: |
          python .github/scripts/check_structure.py
          
      - name: Validate YAML syntax
        run: |
          python .github/scripts/validate_yaml.py
          
      - name: Validate against schema
        run: |
          python .github/scripts/validate_schema.py
          
      - name: Check for required files
        run: |
          python .github/scripts/check_files.py